- name: install terraform
  import_playbook: install_tf.yml

- name: terraform apply
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: terraform init
      command:
        cmd: terraform init
        chdir: ../terraform/
    - name: apply
      terraform:
        project_path: ../terraform/
        lock: true
        state: present
        variables:
          webserver_ip: "{{ webserver_ip }}"
      tags:
        - apply
